version: '3.7'

services:
  mariadb:
    container_name: 'mariadb'
    image: 'bitnami/mariadb:10.1.37'
    restart: 'always'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bitnami_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - back

volumes:
  mariadb_data:
    driver: 'local'

networks:
  back:
    driver: overlay
    ipam:
      config:
        - subnet: 10.255.0.0/16
