version: '3.7'

services:
  mariadb:
    container_name: 'mariadb'
    image: 'bitnami/mariadb:10.1.37'
    restart: 'always'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bitnami_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - moodle
  moodle:
    container_name: 'moodle'
    image: 'bitnami/moodle:3.5.2'
    restart: 'always'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bitnami_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - 'mariadb'
    networks:
      - moodle

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,hard,nolock,proto=tcp
      device: ":/nfs/volumes/mariadb"
  moodle_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,hard,nolock,proto=tcp
      device: ":/nfs/volumes/moodle"

networks:
  moodle:
    driver: bridge
